//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5485
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DH.PaymentAllocationService
{
    using System.Runtime.Serialization;


    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "InRuleRequest", Namespace = "http://schemas.datacontract.org/2004/07/DH.PaymentAllocationService")]
    public partial class InRuleRequest : object, System.Runtime.Serialization.IExtensibleDataObject
    {

        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        private DH.PaymentAllocationObjects.Error[] ErrorDetailsField;

        private string RuleDataXMLField;

        private DH.PaymentAllocationService.RuleInfo RuleInfoField;

        private string StatusField;

        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public DH.PaymentAllocationObjects.Error[] ErrorDetails
        {
            get
            {
                return this.ErrorDetailsField;
            }
            set
            {
                this.ErrorDetailsField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RuleDataXML
        {
            get
            {
                return this.RuleDataXMLField;
            }
            set
            {
                this.RuleDataXMLField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public DH.PaymentAllocationService.RuleInfo RuleInfo
        {
            get
            {
                return this.RuleInfoField;
            }
            set
            {
                this.RuleInfoField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Status
        {
            get
            {
                return this.StatusField;
            }
            set
            {
                this.StatusField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "RuleInfo", Namespace = "http://schemas.datacontract.org/2004/07/DH.PaymentAllocationService")]
    public partial class RuleInfo : object, System.Runtime.Serialization.IExtensibleDataObject
    {

        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        private string CallerField;

        private DH.PaymentAllocationObjects.Error[] ErrorDetailsField;

        private string FillerField;

        private string RuleEvaluationDateField;

        private string RuleNameField;

        private string StatusField;

        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Caller
        {
            get
            {
                return this.CallerField;
            }
            set
            {
                this.CallerField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public DH.PaymentAllocationObjects.Error[] ErrorDetails
        {
            get
            {
                return this.ErrorDetailsField;
            }
            set
            {
                this.ErrorDetailsField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Filler
        {
            get
            {
                return this.FillerField;
            }
            set
            {
                this.FillerField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RuleEvaluationDate
        {
            get
            {
                return this.RuleEvaluationDateField;
            }
            set
            {
                this.RuleEvaluationDateField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RuleName
        {
            get
            {
                return this.RuleNameField;
            }
            set
            {
                this.RuleNameField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Status
        {
            get
            {
                return this.StatusField;
            }
            set
            {
                this.StatusField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "InRuleResponse", Namespace = "http://schemas.datacontract.org/2004/07/DH.PaymentAllocationService")]
    public partial class InRuleResponse : object, System.Runtime.Serialization.IExtensibleDataObject
    {

        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        private DH.PaymentAllocationService.RuleInfo RuleInfoField;

        private string RuleResultField;

        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public DH.PaymentAllocationService.RuleInfo RuleInfo
        {
            get
            {
                return this.RuleInfoField;
            }
            set
            {
                this.RuleInfoField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RuleResult
        {
            get
            {
                return this.RuleResultField;
            }
            set
            {
                this.RuleResultField = value;
            }
        }
    }
}
namespace DH.PaymentAllocationObjects
{
    using System.Runtime.Serialization;


    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "Error", Namespace = "http://schemas.datacontract.org/2004/07/DH.PaymentAllocationObjects")]
    public partial class Error : object, System.Runtime.Serialization.IExtensibleDataObject
    {

        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        private string MessageField;

        private string NumberField;

        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message
        {
            get
            {
                return this.MessageField;
            }
            set
            {
                this.MessageField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Number
        {
            get
            {
                return this.NumberField;
            }
            set
            {
                this.NumberField = value;
            }
        }
    }
}


[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(Namespace = "http://dh.com/inruleservice/", ConfigurationName = "IInRuleService")]
public interface IInRuleService
{

    [System.ServiceModel.OperationContractAttribute(Action = "http://dh.com/inruleservice/IInRuleService/PaymentAllocationRules", ReplyAction = "http://dh.com/inruleservice/IInRuleService/PaymentAllocationRulesResponse")]
    DH.PaymentAllocationService.InRuleResponse PaymentAllocationRules(DH.PaymentAllocationService.InRuleRequest request);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
public interface IInRuleServiceChannel : IInRuleService, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
public partial class InRuleServiceClient : System.ServiceModel.ClientBase<IInRuleService>, IInRuleService
{

    public InRuleServiceClient()
    {
    }

    public InRuleServiceClient(string endpointConfigurationName) :
            base(endpointConfigurationName)
    {
    }

    public InRuleServiceClient(string endpointConfigurationName, string remoteAddress) :
            base(endpointConfigurationName, remoteAddress)
    {
    }

    public InRuleServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) :
            base(endpointConfigurationName, remoteAddress)
    {
    }

    public InRuleServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) :
            base(binding, remoteAddress)
    {
    }

    public DH.PaymentAllocationService.InRuleResponse PaymentAllocationRules(DH.PaymentAllocationService.InRuleRequest request)
    {
        return base.Channel.PaymentAllocationRules(request);
    }
}