//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DH.PaymentAllocationService.Tests.InRulePaymentAllocationService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InRuleRequest", Namespace="http://schemas.datacontract.org/2004/07/DH.PaymentAllocationService")]
    [System.SerializableAttribute()]
    public partial class InRuleRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<DH.PaymentAllocationService.Tests.InRulePaymentAllocationService.Error> ErrorDetailsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RuleDataXMLField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private DH.PaymentAllocationService.Tests.InRulePaymentAllocationService.RuleInfo RuleInfoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StatusField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<DH.PaymentAllocationService.Tests.InRulePaymentAllocationService.Error> ErrorDetails {
            get {
                return this.ErrorDetailsField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorDetailsField, value) != true)) {
                    this.ErrorDetailsField = value;
                    this.RaisePropertyChanged("ErrorDetails");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RuleDataXML {
            get {
                return this.RuleDataXMLField;
            }
            set {
                if ((object.ReferenceEquals(this.RuleDataXMLField, value) != true)) {
                    this.RuleDataXMLField = value;
                    this.RaisePropertyChanged("RuleDataXML");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public DH.PaymentAllocationService.Tests.InRulePaymentAllocationService.RuleInfo RuleInfo {
            get {
                return this.RuleInfoField;
            }
            set {
                if ((object.ReferenceEquals(this.RuleInfoField, value) != true)) {
                    this.RuleInfoField = value;
                    this.RaisePropertyChanged("RuleInfo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Status {
            get {
                return this.StatusField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusField, value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RuleInfo", Namespace="http://schemas.datacontract.org/2004/07/DH.PaymentAllocationService")]
    [System.SerializableAttribute()]
    public partial class RuleInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CallerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<DH.PaymentAllocationService.Tests.InRulePaymentAllocationService.Error> ErrorDetailsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FillerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RuleEvaluationDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RuleNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StatusField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Caller {
            get {
                return this.CallerField;
            }
            set {
                if ((object.ReferenceEquals(this.CallerField, value) != true)) {
                    this.CallerField = value;
                    this.RaisePropertyChanged("Caller");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<DH.PaymentAllocationService.Tests.InRulePaymentAllocationService.Error> ErrorDetails {
            get {
                return this.ErrorDetailsField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorDetailsField, value) != true)) {
                    this.ErrorDetailsField = value;
                    this.RaisePropertyChanged("ErrorDetails");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Filler {
            get {
                return this.FillerField;
            }
            set {
                if ((object.ReferenceEquals(this.FillerField, value) != true)) {
                    this.FillerField = value;
                    this.RaisePropertyChanged("Filler");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RuleEvaluationDate {
            get {
                return this.RuleEvaluationDateField;
            }
            set {
                if ((object.ReferenceEquals(this.RuleEvaluationDateField, value) != true)) {
                    this.RuleEvaluationDateField = value;
                    this.RaisePropertyChanged("RuleEvaluationDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RuleName {
            get {
                return this.RuleNameField;
            }
            set {
                if ((object.ReferenceEquals(this.RuleNameField, value) != true)) {
                    this.RuleNameField = value;
                    this.RaisePropertyChanged("RuleName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Status {
            get {
                return this.StatusField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusField, value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Error", Namespace="http://schemas.datacontract.org/2004/07/DH.PaymentAllocationObjects")]
    [System.SerializableAttribute()]
    public partial class Error : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NumberField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Number {
            get {
                return this.NumberField;
            }
            set {
                if ((object.ReferenceEquals(this.NumberField, value) != true)) {
                    this.NumberField = value;
                    this.RaisePropertyChanged("Number");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InRuleResponse", Namespace="http://schemas.datacontract.org/2004/07/DH.PaymentAllocationService")]
    [System.SerializableAttribute()]
    public partial class InRuleResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private DH.PaymentAllocationService.Tests.InRulePaymentAllocationService.RuleInfo RuleInfoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RuleResultField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public DH.PaymentAllocationService.Tests.InRulePaymentAllocationService.RuleInfo RuleInfo {
            get {
                return this.RuleInfoField;
            }
            set {
                if ((object.ReferenceEquals(this.RuleInfoField, value) != true)) {
                    this.RuleInfoField = value;
                    this.RaisePropertyChanged("RuleInfo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RuleResult {
            get {
                return this.RuleResultField;
            }
            set {
                if ((object.ReferenceEquals(this.RuleResultField, value) != true)) {
                    this.RuleResultField = value;
                    this.RaisePropertyChanged("RuleResult");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://dh.com/inruleservice/", ConfigurationName="InRulePaymentAllocationService.IInRuleService")]
    public interface IInRuleService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://dh.com/inruleservice/IInRuleService/PaymentAllocationRules", ReplyAction="http://dh.com/inruleservice/IInRuleService/PaymentAllocationRulesResponse")]
        DH.PaymentAllocationService.Tests.InRulePaymentAllocationService.InRuleResponse PaymentAllocationRules(DH.PaymentAllocationService.Tests.InRulePaymentAllocationService.InRuleRequest request);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IInRuleServiceChannel : DH.PaymentAllocationService.Tests.InRulePaymentAllocationService.IInRuleService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class InRuleServiceClient : System.ServiceModel.ClientBase<DH.PaymentAllocationService.Tests.InRulePaymentAllocationService.IInRuleService>, DH.PaymentAllocationService.Tests.InRulePaymentAllocationService.IInRuleService {
        
        public InRuleServiceClient() {
        }
        
        public InRuleServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public InRuleServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public InRuleServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public InRuleServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public DH.PaymentAllocationService.Tests.InRulePaymentAllocationService.InRuleResponse PaymentAllocationRules(DH.PaymentAllocationService.Tests.InRulePaymentAllocationService.InRuleRequest request) {
            return base.Channel.PaymentAllocationRules(request);
        }
    }
}
